# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from stroeer.page.article.v1 import article_page_service_pb2 as stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2


class ArticlePageServiceStub(object):
    """*
    ```protobuf
    service ArticlePageService {
    # turns the requested article with editorial render relevant data for the user and SEO bots.
    rpc GetArticlePage (GetArticlePageRequest) returns (GetArticlePageResponse) {}

    # request data to render Article Companions as individual html for esi integration on ArticlePages
    rpc GetArticleCompanions (GetArticleCompanionsRequest) returns (GetArticleCompanionsResponse) {}
    }
    ```
    # Description


    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArticlePage = channel.unary_unary(
                '/stroeer.page.article.v1.ArticlePageService/GetArticlePage',
                request_serializer=stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticlePageRequest.SerializeToString,
                response_deserializer=stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticlePageResponse.FromString,
                )
        self.GetArticleCompanions = channel.unary_unary(
                '/stroeer.page.article.v1.ArticlePageService/GetArticleCompanions',
                request_serializer=stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticleCompanionsRequest.SerializeToString,
                response_deserializer=stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticleCompanionsResponse.FromString,
                )


class ArticlePageServiceServicer(object):
    """*
    ```protobuf
    service ArticlePageService {
    # turns the requested article with editorial render relevant data for the user and SEO bots.
    rpc GetArticlePage (GetArticlePageRequest) returns (GetArticlePageResponse) {}

    # request data to render Article Companions as individual html for esi integration on ArticlePages
    rpc GetArticleCompanions (GetArticleCompanionsRequest) returns (GetArticleCompanionsResponse) {}
    }
    ```
    # Description


    """

    def GetArticlePage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticleCompanions(self, request, context):
        """request data to render Article Companions as individual html for esi integration on ArticlePages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArticlePageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetArticlePage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticlePage,
                    request_deserializer=stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticlePageRequest.FromString,
                    response_serializer=stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticlePageResponse.SerializeToString,
            ),
            'GetArticleCompanions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticleCompanions,
                    request_deserializer=stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticleCompanionsRequest.FromString,
                    response_serializer=stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticleCompanionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stroeer.page.article.v1.ArticlePageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArticlePageService(object):
    """*
    ```protobuf
    service ArticlePageService {
    # turns the requested article with editorial render relevant data for the user and SEO bots.
    rpc GetArticlePage (GetArticlePageRequest) returns (GetArticlePageResponse) {}

    # request data to render Article Companions as individual html for esi integration on ArticlePages
    rpc GetArticleCompanions (GetArticleCompanionsRequest) returns (GetArticleCompanionsResponse) {}
    }
    ```
    # Description


    """

    @staticmethod
    def GetArticlePage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stroeer.page.article.v1.ArticlePageService/GetArticlePage',
            stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticlePageRequest.SerializeToString,
            stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticlePageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetArticleCompanions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stroeer.page.article.v1.ArticlePageService/GetArticleCompanions',
            stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticleCompanionsRequest.SerializeToString,
            stroeer_dot_page_dot_article_dot_v1_dot_article__page__service__pb2.GetArticleCompanionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
