# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stroeer/page/article/v1/article_page.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from stroeer.core.v1 import article_pb2 as stroeer_dot_core_dot_v1_dot_article__pb2
from stroeer.core.v1 import shared_pb2 as stroeer_dot_core_dot_v1_dot_shared__pb2
from stroeer.page.stage.v1 import stage_pb2 as stroeer_dot_page_dot_stage_dot_v1_dot_stage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*stroeer/page/article/v1/article_page.proto\x12\x17stroeer.page.article.v1\x1a\x1dstroeer/core/v1/article.proto\x1a\x1cstroeer/core/v1/shared.proto\x1a!stroeer/page/stage/v1/stage.proto\"\x9b\x01\n\x0b\x41rticlePage\x12)\n\x07\x61rticle\x18\x01 \x01(\x0b\x32\x18.stroeer.core.v1.Article\x12,\n\x06stages\x18\x03 \x03(\x0b\x32\x1c.stroeer.page.stage.v1.Stage\x12\x33\n\x0fnavigation_menu\x18\x04 \x01(\x0b\x32\x1a.stroeer.core.v1.ReferenceB5Z3github.com/stroeer/go-tapir/page/article/v1;articleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stroeer.page.article.v1.article_page_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/stroeer/go-tapir/page/article/v1;article'
  _globals['_ARTICLEPAGE']._serialized_start=168
  _globals['_ARTICLEPAGE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
