# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stroeer/page/article/v1/article_page.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from stroeer.core.v1 import article_pb2 as stroeer_dot_core_dot_v1_dot_article__pb2
from stroeer.page.stage.v1 import stage_pb2 as stroeer_dot_page_dot_stage_dot_v1_dot_stage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*stroeer/page/article/v1/article_page.proto\x12\x17stroeer.page.article.v1\x1a\x1dstroeer/core/v1/article.proto\x1a!stroeer/page/stage/v1/stage.proto\"\xe0\x01\n\x0b\x41rticlePage\x12)\n\x07\x61rticle\x18\x01 \x01(\x0b\x32\x18.stroeer.core.v1.Article\x12\x41\n\x10related_articles\x18\x02 \x03(\x0b\x32\'.stroeer.page.article.v1.RelatedArticle\x12,\n\x06stages\x18\x03 \x03(\x0b\x32\x1c.stroeer.page.stage.v1.Stage\x12\x35\n\ncompanions\x18\x04 \x03(\x0b\x32!.stroeer.page.stage.v1.Stage.Item\"z\n\x0eRelatedArticle\x12)\n\x07\x61rticle\x18\x01 \x01(\x0b\x32\x18.stroeer.core.v1.Article\x12=\n\x06source\x18\x02 \x01(\x0e\x32-.stroeer.page.article.v1.RelatedArticleSource*d\n\x14RelatedArticleSource\x12&\n\"RELATED_ARTICLE_SOURCE_UNSPECIFIED\x10\x00\x12$\n RELATED_ARTICLE_SOURCE_EDITORIAL\x10\x01\x42S\n\x1a\x64\x65.stroeer.page.article.v1P\x01Z3github.com/stroeer/go-tapir/page/article/v1;articleb\x06proto3')

_RELATEDARTICLESOURCE = DESCRIPTOR.enum_types_by_name['RelatedArticleSource']
RelatedArticleSource = enum_type_wrapper.EnumTypeWrapper(_RELATEDARTICLESOURCE)
RELATED_ARTICLE_SOURCE_UNSPECIFIED = 0
RELATED_ARTICLE_SOURCE_EDITORIAL = 1


_ARTICLEPAGE = DESCRIPTOR.message_types_by_name['ArticlePage']
_RELATEDARTICLE = DESCRIPTOR.message_types_by_name['RelatedArticle']
ArticlePage = _reflection.GeneratedProtocolMessageType('ArticlePage', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLEPAGE,
  '__module__' : 'stroeer.page.article.v1.article_page_pb2'
  # @@protoc_insertion_point(class_scope:stroeer.page.article.v1.ArticlePage)
  })
_sym_db.RegisterMessage(ArticlePage)

RelatedArticle = _reflection.GeneratedProtocolMessageType('RelatedArticle', (_message.Message,), {
  'DESCRIPTOR' : _RELATEDARTICLE,
  '__module__' : 'stroeer.page.article.v1.article_page_pb2'
  # @@protoc_insertion_point(class_scope:stroeer.page.article.v1.RelatedArticle)
  })
_sym_db.RegisterMessage(RelatedArticle)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032de.stroeer.page.article.v1P\001Z3github.com/stroeer/go-tapir/page/article/v1;article'
  _RELATEDARTICLESOURCE._serialized_start=488
  _RELATEDARTICLESOURCE._serialized_end=588
  _ARTICLEPAGE._serialized_start=138
  _ARTICLEPAGE._serialized_end=362
  _RELATEDARTICLE._serialized_start=364
  _RELATEDARTICLE._serialized_end=486
# @@protoc_insertion_point(module_scope)
