# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stroeer/page/stage/v1/stage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from stroeer.core.v1 import article_pb2 as stroeer_dot_core_dot_v1_dot_article__pb2
from stroeer.core.v1 import shared_pb2 as stroeer_dot_core_dot_v1_dot_shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!stroeer/page/stage/v1/stage.proto\x12\x15stroeer.page.stage.v1\x1a\x1dstroeer/core/v1/article.proto\x1a\x1cstroeer/core/v1/shared.proto\"\xfb\x07\n\x05Stage\x12\x41\n\rconfiguration\x18\x01 \x01(\x0b\x32*.stroeer.page.stage.v1.Stage.Configuration\x12\x37\n\x0cstream_items\x18\x02 \x03(\x0b\x32!.stroeer.page.stage.v1.Stage.Item\x12:\n\x0f\x63ompanion_items\x18\x03 \x03(\x0b\x32!.stroeer.page.stage.v1.Stage.Item\x1a\xb6\x01\n\rConfiguration\x12\x46\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x36.stroeer.page.stage.v1.Stage.Configuration.FieldsEntry\x12.\n\nreferences\x18\x02 \x03(\x0b\x32\x1a.stroeer.core.v1.Reference\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x80\x05\n\x04Item\x12=\n\x06\x66ields\x18\x01 \x03(\x0b\x32-.stroeer.page.stage.v1.Stage.Item.FieldsEntry\x12-\n\x05stage\x18\x02 \x01(\x0b\x32\x1c.stroeer.page.stage.v1.StageH\x00\x12I\n\x0e\x61rticle_teaser\x18\x03 \x01(\x0b\x32/.stroeer.page.stage.v1.Stage.Item.ArticleTeaserH\x00\x12\x42\n\ncommercial\x18\x04 \x01(\x0b\x32,.stroeer.page.stage.v1.Stage.Item.CommercialH\x00\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\xb6\x01\n\rArticleTeaser\x12K\n\x06\x66ields\x18\x01 \x03(\x0b\x32;.stroeer.page.stage.v1.Stage.Item.ArticleTeaser.FieldsEntry\x12)\n\x07\x61rticle\x18\x02 \x01(\x0b\x32\x18.stroeer.core.v1.Article\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x85\x01\n\nCommercial\x12H\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x38.stroeer.page.stage.v1.Stage.Item.Commercial.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0b\n\titem_typeBM\n\x18\x64\x65.stroeer.page.stage.v1P\x01Z/github.com/stroeer/go-tapir/page/stage/v1;stageb\x06proto3')



_STAGE = DESCRIPTOR.message_types_by_name['Stage']
_STAGE_CONFIGURATION = _STAGE.nested_types_by_name['Configuration']
_STAGE_CONFIGURATION_FIELDSENTRY = _STAGE_CONFIGURATION.nested_types_by_name['FieldsEntry']
_STAGE_ITEM = _STAGE.nested_types_by_name['Item']
_STAGE_ITEM_FIELDSENTRY = _STAGE_ITEM.nested_types_by_name['FieldsEntry']
_STAGE_ITEM_ARTICLETEASER = _STAGE_ITEM.nested_types_by_name['ArticleTeaser']
_STAGE_ITEM_ARTICLETEASER_FIELDSENTRY = _STAGE_ITEM_ARTICLETEASER.nested_types_by_name['FieldsEntry']
_STAGE_ITEM_COMMERCIAL = _STAGE_ITEM.nested_types_by_name['Commercial']
_STAGE_ITEM_COMMERCIAL_FIELDSENTRY = _STAGE_ITEM_COMMERCIAL.nested_types_by_name['FieldsEntry']
Stage = _reflection.GeneratedProtocolMessageType('Stage', (_message.Message,), {

  'Configuration' : _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), {

    'FieldsEntry' : _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), {
      'DESCRIPTOR' : _STAGE_CONFIGURATION_FIELDSENTRY,
      '__module__' : 'stroeer.page.stage.v1.stage_pb2'
      # @@protoc_insertion_point(class_scope:stroeer.page.stage.v1.Stage.Configuration.FieldsEntry)
      })
    ,
    'DESCRIPTOR' : _STAGE_CONFIGURATION,
    '__module__' : 'stroeer.page.stage.v1.stage_pb2'
    # @@protoc_insertion_point(class_scope:stroeer.page.stage.v1.Stage.Configuration)
    })
  ,

  'Item' : _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {

    'FieldsEntry' : _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), {
      'DESCRIPTOR' : _STAGE_ITEM_FIELDSENTRY,
      '__module__' : 'stroeer.page.stage.v1.stage_pb2'
      # @@protoc_insertion_point(class_scope:stroeer.page.stage.v1.Stage.Item.FieldsEntry)
      })
    ,

    'ArticleTeaser' : _reflection.GeneratedProtocolMessageType('ArticleTeaser', (_message.Message,), {

      'FieldsEntry' : _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), {
        'DESCRIPTOR' : _STAGE_ITEM_ARTICLETEASER_FIELDSENTRY,
        '__module__' : 'stroeer.page.stage.v1.stage_pb2'
        # @@protoc_insertion_point(class_scope:stroeer.page.stage.v1.Stage.Item.ArticleTeaser.FieldsEntry)
        })
      ,
      'DESCRIPTOR' : _STAGE_ITEM_ARTICLETEASER,
      '__module__' : 'stroeer.page.stage.v1.stage_pb2'
      # @@protoc_insertion_point(class_scope:stroeer.page.stage.v1.Stage.Item.ArticleTeaser)
      })
    ,

    'Commercial' : _reflection.GeneratedProtocolMessageType('Commercial', (_message.Message,), {

      'FieldsEntry' : _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), {
        'DESCRIPTOR' : _STAGE_ITEM_COMMERCIAL_FIELDSENTRY,
        '__module__' : 'stroeer.page.stage.v1.stage_pb2'
        # @@protoc_insertion_point(class_scope:stroeer.page.stage.v1.Stage.Item.Commercial.FieldsEntry)
        })
      ,
      'DESCRIPTOR' : _STAGE_ITEM_COMMERCIAL,
      '__module__' : 'stroeer.page.stage.v1.stage_pb2'
      # @@protoc_insertion_point(class_scope:stroeer.page.stage.v1.Stage.Item.Commercial)
      })
    ,
    'DESCRIPTOR' : _STAGE_ITEM,
    '__module__' : 'stroeer.page.stage.v1.stage_pb2'
    # @@protoc_insertion_point(class_scope:stroeer.page.stage.v1.Stage.Item)
    })
  ,
  'DESCRIPTOR' : _STAGE,
  '__module__' : 'stroeer.page.stage.v1.stage_pb2'
  # @@protoc_insertion_point(class_scope:stroeer.page.stage.v1.Stage)
  })
_sym_db.RegisterMessage(Stage)
_sym_db.RegisterMessage(Stage.Configuration)
_sym_db.RegisterMessage(Stage.Configuration.FieldsEntry)
_sym_db.RegisterMessage(Stage.Item)
_sym_db.RegisterMessage(Stage.Item.FieldsEntry)
_sym_db.RegisterMessage(Stage.Item.ArticleTeaser)
_sym_db.RegisterMessage(Stage.Item.ArticleTeaser.FieldsEntry)
_sym_db.RegisterMessage(Stage.Item.Commercial)
_sym_db.RegisterMessage(Stage.Item.Commercial.FieldsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030de.stroeer.page.stage.v1P\001Z/github.com/stroeer/go-tapir/page/stage/v1;stage'
  _STAGE_CONFIGURATION_FIELDSENTRY._options = None
  _STAGE_CONFIGURATION_FIELDSENTRY._serialized_options = b'8\001'
  _STAGE_ITEM_FIELDSENTRY._options = None
  _STAGE_ITEM_FIELDSENTRY._serialized_options = b'8\001'
  _STAGE_ITEM_ARTICLETEASER_FIELDSENTRY._options = None
  _STAGE_ITEM_ARTICLETEASER_FIELDSENTRY._serialized_options = b'8\001'
  _STAGE_ITEM_COMMERCIAL_FIELDSENTRY._options = None
  _STAGE_ITEM_COMMERCIAL_FIELDSENTRY._serialized_options = b'8\001'
  _STAGE._serialized_start=122
  _STAGE._serialized_end=1141
  _STAGE_CONFIGURATION._serialized_start=316
  _STAGE_CONFIGURATION._serialized_end=498
  _STAGE_CONFIGURATION_FIELDSENTRY._serialized_start=453
  _STAGE_CONFIGURATION_FIELDSENTRY._serialized_end=498
  _STAGE_ITEM._serialized_start=501
  _STAGE_ITEM._serialized_end=1141
  _STAGE_ITEM_FIELDSENTRY._serialized_start=453
  _STAGE_ITEM_FIELDSENTRY._serialized_end=498
  _STAGE_ITEM_ARTICLETEASER._serialized_start=810
  _STAGE_ITEM_ARTICLETEASER._serialized_end=992
  _STAGE_ITEM_ARTICLETEASER_FIELDSENTRY._serialized_start=453
  _STAGE_ITEM_ARTICLETEASER_FIELDSENTRY._serialized_end=498
  _STAGE_ITEM_COMMERCIAL._serialized_start=995
  _STAGE_ITEM_COMMERCIAL._serialized_end=1128
  _STAGE_ITEM_COMMERCIAL_FIELDSENTRY._serialized_start=453
  _STAGE_ITEM_COMMERCIAL_FIELDSENTRY._serialized_end=498
# @@protoc_insertion_point(module_scope)
