# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from stroeer.page.section.v1 import section_page_service_pb2 as stroeer_dot_page_dot_section_dot_v1_dot_section__page__service__pb2


class SectionPageServiceStub(object):
    """*
    Service to fetch all data needed to render a section page, like the homepage or "/politik/"
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSectionPage = channel.unary_unary(
                '/stroeer.page.section.v1.SectionPageService/GetSectionPage',
                request_serializer=stroeer_dot_page_dot_section_dot_v1_dot_section__page__service__pb2.GetSectionPageRequest.SerializeToString,
                response_deserializer=stroeer_dot_page_dot_section_dot_v1_dot_section__page__service__pb2.GetSectionPageResponse.FromString,
                )


class SectionPageServiceServicer(object):
    """*
    Service to fetch all data needed to render a section page, like the homepage or "/politik/"
    """

    def GetSectionPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SectionPageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSectionPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSectionPage,
                    request_deserializer=stroeer_dot_page_dot_section_dot_v1_dot_section__page__service__pb2.GetSectionPageRequest.FromString,
                    response_serializer=stroeer_dot_page_dot_section_dot_v1_dot_section__page__service__pb2.GetSectionPageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stroeer.page.section.v1.SectionPageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SectionPageService(object):
    """*
    Service to fetch all data needed to render a section page, like the homepage or "/politik/"
    """

    @staticmethod
    def GetSectionPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stroeer.page.section.v1.SectionPageService/GetSectionPage',
            stroeer_dot_page_dot_section_dot_v1_dot_section__page__service__pb2.GetSectionPageRequest.SerializeToString,
            stroeer_dot_page_dot_section_dot_v1_dot_section__page__service__pb2.GetSectionPageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
