# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stroeer/page/section/v1/section_page.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from stroeer.core.v1 import shared_pb2 as stroeer_dot_core_dot_v1_dot_shared__pb2
from stroeer.page.stage.v1 import stage_pb2 as stroeer_dot_page_dot_stage_dot_v1_dot_stage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stroeer/page/section/v1/section_page.proto',
  package='stroeer.page.section.v1',
  syntax='proto3',
  serialized_options=b'\n\032de.stroeer.page.section.v1P\001Z3github.com/stroeer/go-tapir/page/section/v1;section',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*stroeer/page/section/v1/section_page.proto\x12\x17stroeer.page.section.v1\x1a\x1cstroeer/core/v1/shared.proto\x1a!stroeer/page/stage/v1/stage.proto\"\xb1\x02\n\x0bSectionPage\x12=\n\x07section\x18\x01 \x01(\x0b\x32,.stroeer.page.section.v1.SectionPage.Section\x12,\n\x06stages\x18\x02 \x03(\x0b\x32\x1c.stroeer.page.stage.v1.Stage\x1a\xb4\x01\n\x07Section\x12H\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x38.stroeer.page.section.v1.SectionPage.Section.FieldsEntry\x12\x30\n\x0csection_tree\x18\x02 \x01(\x0b\x32\x1a.stroeer.core.v1.Reference\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42S\n\x1a\x64\x65.stroeer.page.section.v1P\x01Z3github.com/stroeer/go-tapir/page/section/v1;sectionb\x06proto3'
  ,
  dependencies=[stroeer_dot_core_dot_v1_dot_shared__pb2.DESCRIPTOR,stroeer_dot_page_dot_stage_dot_v1_dot_stage__pb2.DESCRIPTOR,])




_SECTIONPAGE_SECTION_FIELDSENTRY = _descriptor.Descriptor(
  name='FieldsEntry',
  full_name='stroeer.page.section.v1.SectionPage.Section.FieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='stroeer.page.section.v1.SectionPage.Section.FieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='stroeer.page.section.v1.SectionPage.Section.FieldsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=442,
)

_SECTIONPAGE_SECTION = _descriptor.Descriptor(
  name='Section',
  full_name='stroeer.page.section.v1.SectionPage.Section',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='stroeer.page.section.v1.SectionPage.Section.fields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='section_tree', full_name='stroeer.page.section.v1.SectionPage.Section.section_tree', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SECTIONPAGE_SECTION_FIELDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=442,
)

_SECTIONPAGE = _descriptor.Descriptor(
  name='SectionPage',
  full_name='stroeer.page.section.v1.SectionPage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='section', full_name='stroeer.page.section.v1.SectionPage.section', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stages', full_name='stroeer.page.section.v1.SectionPage.stages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SECTIONPAGE_SECTION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=442,
)

_SECTIONPAGE_SECTION_FIELDSENTRY.containing_type = _SECTIONPAGE_SECTION
_SECTIONPAGE_SECTION.fields_by_name['fields'].message_type = _SECTIONPAGE_SECTION_FIELDSENTRY
_SECTIONPAGE_SECTION.fields_by_name['section_tree'].message_type = stroeer_dot_core_dot_v1_dot_shared__pb2._REFERENCE
_SECTIONPAGE_SECTION.containing_type = _SECTIONPAGE
_SECTIONPAGE.fields_by_name['section'].message_type = _SECTIONPAGE_SECTION
_SECTIONPAGE.fields_by_name['stages'].message_type = stroeer_dot_page_dot_stage_dot_v1_dot_stage__pb2._STAGE
DESCRIPTOR.message_types_by_name['SectionPage'] = _SECTIONPAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SectionPage = _reflection.GeneratedProtocolMessageType('SectionPage', (_message.Message,), {

  'Section' : _reflection.GeneratedProtocolMessageType('Section', (_message.Message,), {

    'FieldsEntry' : _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), {
      'DESCRIPTOR' : _SECTIONPAGE_SECTION_FIELDSENTRY,
      '__module__' : 'stroeer.page.section.v1.section_page_pb2'
      # @@protoc_insertion_point(class_scope:stroeer.page.section.v1.SectionPage.Section.FieldsEntry)
      })
    ,
    'DESCRIPTOR' : _SECTIONPAGE_SECTION,
    '__module__' : 'stroeer.page.section.v1.section_page_pb2'
    # @@protoc_insertion_point(class_scope:stroeer.page.section.v1.SectionPage.Section)
    })
  ,
  'DESCRIPTOR' : _SECTIONPAGE,
  '__module__' : 'stroeer.page.section.v1.section_page_pb2'
  # @@protoc_insertion_point(class_scope:stroeer.page.section.v1.SectionPage)
  })
_sym_db.RegisterMessage(SectionPage)
_sym_db.RegisterMessage(SectionPage.Section)
_sym_db.RegisterMessage(SectionPage.Section.FieldsEntry)


DESCRIPTOR._options = None
_SECTIONPAGE_SECTION_FIELDSENTRY._options = None
# @@protoc_insertion_point(module_scope)
