# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stroeer/navigation/v1/navigation_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from stroeer.core.v1 import shared_pb2 as stroeer_dot_core_dot_v1_dot_shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.stroeer/navigation/v1/navigation_service.proto\x12\x15stroeer.navigation.v1\x1a\x1cstroeer/core/v1/shared.proto\"\x16\n\x14GetNavigationRequest\"L\n\x15GetNavigationResponse\x12\x33\n\x0fnavigation_menu\x18\x01 \x01(\x0b\x32\x1a.stroeer.core.v1.Reference2\x81\x01\n\x11NavigationService\x12l\n\rGetNavigation\x12+.stroeer.navigation.v1.GetNavigationRequest\x1a,.stroeer.navigation.v1.GetNavigationResponse\"\x00\x42\x36Z4github.com/stroeer/go-tapir/navigation/v1;navigationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stroeer.navigation.v1.navigation_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z4github.com/stroeer/go-tapir/navigation/v1;navigation'
  _globals['_GETNAVIGATIONREQUEST']._serialized_start=103
  _globals['_GETNAVIGATIONREQUEST']._serialized_end=125
  _globals['_GETNAVIGATIONRESPONSE']._serialized_start=127
  _globals['_GETNAVIGATIONRESPONSE']._serialized_end=203
  _globals['_NAVIGATIONSERVICE']._serialized_start=206
  _globals['_NAVIGATIONSERVICE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
