# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from stroeer.navigation.v1 import navigation_service_pb2 as stroeer_dot_navigation_dot_v1_dot_navigation__service__pb2


class NavigationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNavigation = channel.unary_unary(
                '/stroeer.navigation.v1.NavigationService/GetNavigation',
                request_serializer=stroeer_dot_navigation_dot_v1_dot_navigation__service__pb2.GetNavigationRequest.SerializeToString,
                response_deserializer=stroeer_dot_navigation_dot_v1_dot_navigation__service__pb2.GetNavigationResponse.FromString,
                )


class NavigationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNavigation(self, request, context):
        """Retrieve navigation tree structure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NavigationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNavigation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNavigation,
                    request_deserializer=stroeer_dot_navigation_dot_v1_dot_navigation__service__pb2.GetNavigationRequest.FromString,
                    response_serializer=stroeer_dot_navigation_dot_v1_dot_navigation__service__pb2.GetNavigationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stroeer.navigation.v1.NavigationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NavigationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNavigation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stroeer.navigation.v1.NavigationService/GetNavigation',
            stroeer_dot_navigation_dot_v1_dot_navigation__service__pb2.GetNavigationRequest.SerializeToString,
            stroeer_dot_navigation_dot_v1_dot_navigation__service__pb2.GetNavigationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
