# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stroeer/page/section/v1/section_page_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from stroeer.page.section.v1 import section_page_pb2 as stroeer_dot_page_dot_section_dot_v1_dot_section__page__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stroeer/page/section/v1/section_page_service.proto',
  package='stroeer.page.section.v1',
  syntax='proto3',
  serialized_options=b'\n\032de.stroeer.page.section.v1P\001Z3github.com/stroeer/go-tapir/page/section/v1;section',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2stroeer/page/section/v1/section_page_service.proto\x12\x17stroeer.page.section.v1\x1a*stroeer/page/section/v1/section_page.proto\";\n\x15GetSectionPageRequest\x12\x14\n\x0csection_path\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\"\x97\x02\n\x16GetSectionPageResponse\x12:\n\x0csection_page\x18\x01 \x01(\x0b\x32$.stroeer.page.section.v1.SectionPage\x12\x13\n\x0btotal_pages\x18\x02 \x01(\x05\x12W\n\x0fpagination_type\x18\x03 \x01(\x0e\x32>.stroeer.page.section.v1.GetSectionPageResponse.PaginationType\"S\n\x0ePaginationType\x12\x1f\n\x1bPAGINATION_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x46IXED_BLOCK\x10\x01\x12\x0f\n\x0bGHOST_BLOCK\x10\x02\x32\x89\x01\n\x12SectionPageService\x12s\n\x0eGetSectionPage\x12..stroeer.page.section.v1.GetSectionPageRequest\x1a/.stroeer.page.section.v1.GetSectionPageResponse\"\x00\x42S\n\x1a\x64\x65.stroeer.page.section.v1P\x01Z3github.com/stroeer/go-tapir/page/section/v1;sectionb\x06proto3'
  ,
  dependencies=[stroeer_dot_page_dot_section_dot_v1_dot_section__page__pb2.DESCRIPTOR,])



_GETSECTIONPAGERESPONSE_PAGINATIONTYPE = _descriptor.EnumDescriptor(
  name='PaginationType',
  full_name='stroeer.page.section.v1.GetSectionPageResponse.PaginationType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PAGINATION_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FIXED_BLOCK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GHOST_BLOCK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=381,
  serialized_end=464,
)
_sym_db.RegisterEnumDescriptor(_GETSECTIONPAGERESPONSE_PAGINATIONTYPE)


_GETSECTIONPAGEREQUEST = _descriptor.Descriptor(
  name='GetSectionPageRequest',
  full_name='stroeer.page.section.v1.GetSectionPageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='section_path', full_name='stroeer.page.section.v1.GetSectionPageRequest.section_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='stroeer.page.section.v1.GetSectionPageRequest.page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=182,
)


_GETSECTIONPAGERESPONSE = _descriptor.Descriptor(
  name='GetSectionPageResponse',
  full_name='stroeer.page.section.v1.GetSectionPageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='section_page', full_name='stroeer.page.section.v1.GetSectionPageResponse.section_page', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_pages', full_name='stroeer.page.section.v1.GetSectionPageResponse.total_pages', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pagination_type', full_name='stroeer.page.section.v1.GetSectionPageResponse.pagination_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETSECTIONPAGERESPONSE_PAGINATIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=464,
)

_GETSECTIONPAGERESPONSE.fields_by_name['section_page'].message_type = stroeer_dot_page_dot_section_dot_v1_dot_section__page__pb2._SECTIONPAGE
_GETSECTIONPAGERESPONSE.fields_by_name['pagination_type'].enum_type = _GETSECTIONPAGERESPONSE_PAGINATIONTYPE
_GETSECTIONPAGERESPONSE_PAGINATIONTYPE.containing_type = _GETSECTIONPAGERESPONSE
DESCRIPTOR.message_types_by_name['GetSectionPageRequest'] = _GETSECTIONPAGEREQUEST
DESCRIPTOR.message_types_by_name['GetSectionPageResponse'] = _GETSECTIONPAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSectionPageRequest = _reflection.GeneratedProtocolMessageType('GetSectionPageRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSECTIONPAGEREQUEST,
  '__module__' : 'stroeer.page.section.v1.section_page_service_pb2'
  # @@protoc_insertion_point(class_scope:stroeer.page.section.v1.GetSectionPageRequest)
  })
_sym_db.RegisterMessage(GetSectionPageRequest)

GetSectionPageResponse = _reflection.GeneratedProtocolMessageType('GetSectionPageResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSECTIONPAGERESPONSE,
  '__module__' : 'stroeer.page.section.v1.section_page_service_pb2'
  # @@protoc_insertion_point(class_scope:stroeer.page.section.v1.GetSectionPageResponse)
  })
_sym_db.RegisterMessage(GetSectionPageResponse)


DESCRIPTOR._options = None

_SECTIONPAGESERVICE = _descriptor.ServiceDescriptor(
  name='SectionPageService',
  full_name='stroeer.page.section.v1.SectionPageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=467,
  serialized_end=604,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSectionPage',
    full_name='stroeer.page.section.v1.SectionPageService.GetSectionPage',
    index=0,
    containing_service=None,
    input_type=_GETSECTIONPAGEREQUEST,
    output_type=_GETSECTIONPAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SECTIONPAGESERVICE)

DESCRIPTOR.services_by_name['SectionPageService'] = _SECTIONPAGESERVICE

# @@protoc_insertion_point(module_scope)
